services:
    hgabka_seo.admin.robots:
        class: Hgabka\SeoBundle\Admin\RobotsAdmin
        tags:
        - { name: sonata.admin, manager_type: orm, group: hg_seo.group, icon: '<i class="fa fa-google"></i>', label: hg_seo.admin.label.robots, label_catalogue: 'HgabkaSeoBundle', label_translator_strategy: 'sonata.admin.label.strategy.underscore' }
        arguments: [null, Hgabka\SeoBundle\Entity\Robots, HgabkaSeoBundle:RobotsAdmin]
        calls:
        - [ setTemplate, ['edit', '@@HgabkaSeo/Admin/Robots/create.html.twig']]

    hgabka_seo.admin.seo:
        class: Hgabka\SeoBundle\Admin\SeoAdmin
        tags:
        - { name: sonata.admin, manager_type: orm, group: hg_seo.group, icon: '<i class="fa fa-android"></i>', label: hg_seo.admin.label.seo, label_catalogue: 'HgabkaSeoBundle', label_translator_strategy: 'sonata.admin.label.strategy.underscore' }
        arguments: [null, Hgabka\SeoBundle\Entity\Seo, HgabkaSeoBundle:SeoAdmin]
        calls:
            - [ setTemplate, ['edit', '@@HgabkaSeo/Admin/Seo/create.html.twig']]

    hgabka_seo.twig.extension:
        class: Hgabka\SeoBundle\Twig\SeoTwigExtension
        arguments: ['@doctrine.orm.entity_manager', '@hgabka_seo.seo_manager']
        tags:
            - { name: twig.extension }

    hgabka_seo.google_analytics.order_preparer:
        class: Hgabka\SeoBundle\Helper\OrderPreparer

    hgabka_seo.google_analytics.order_converter:
        class: Hgabka\SeoBundle\Helper\OrderConverter

    hgabka_seo.google_analytics.twig.extension:
        class: Hgabka\SeoBundle\Twig\GoogleAnalyticsTwigExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setAccountID, [ '%google.analytics.account_id%' ] ]
            - [ setOrderPreparer, [ '@hgabka_seo.google_analytics.order_preparer' ] ]
            - [ setOrderConverter, [ '@hgabka_seo.google_analytics.order_converter' ] ]

    hgabka_seo.node.listener:
        class: Hgabka\SeoBundle\EventListener\NodeListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: hgabka_node.adaptForm, method: adaptForm }

    hgabka_seo.clone.listener:
        class: Hgabka\SeoBundle\EventListener\CloneListener
        arguments: ['@doctrine.orm.entity_manager', '@hgabka_utils.clone.helper']
        tags:
            - { name: kernel.event_listener, event: hgabka_utils.postDeepCloneAndSave, method: postDeepCloneAndSave }

    Hgabka\SeoBundle\Admin\Menu\AdminMenuListener:
        autowire: true
        arguments: ['@hgabka_seo.admin.seo', '@hgabka_seo.admin.robots']
        tags:
        - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }

    hgabka_seo.seo_manager:
        alias: Hgabka\SeoBundle\Helper\SeoManager

    Hgabka\SeoBundle\Helper\SeoManager:
        autoconfigure: true
        autowire: true
        arguments:
            $websiteTitle: '%websitetitle%'

    Hgabka\SeoBundle\Repository\SeoRepository:
        autoconfigure: true
        autowire: true

