services:
    hgabka_seo.admin.seo:
        class: Hgabka\SeoBundle\Admin\SeoAdmin
        tags:
        - { name: sonata.admin, manager_type: orm, group: hg_seo.group, icon: '<i class="fa fa-share-square"></i>', label: hg_media.admin.label, label_catalogue: 'HgabkaMediaBundle', label_translator_strategy: 'sonata.admin.label.strategy.underscore' }
        arguments: [null, Hgabka\SeoBundle\Entity\Robots, HgabkaSeoBundle:SeoAdmin]

    hgabka_seo.twig.extension:
        class: Hgabka\SeoBundle\Twig\SeoTwigExtension
        arguments: ['@doctrine.orm.entity_manager']
        calls:
            - [setWebsiteTitle, ['%websitetitle%']]
        tags:
            - { name: twig.extension }

    hgabka_seo.google_analytics.order_preparer:
        class: Hgabka\SeoBundle\Helper\OrderPreparer

    hgabka_seo.google_analytics.order_converter:
        class: Hgabka\SeoBundle\Helper\OrderConverter

    hgabka_seo.google_analytics.twig.extension:
        class: Hgabka\SeoBundle\Twig\GoogleAnalyticsTwigExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setAccountID, [ '%google.analytics.account_id%' ] ]
            - [ setOrderPreparer, [ '@hgabka_seo.google_analytics.order_preparer' ] ]
            - [ setOrderConverter, [ '@hgabka_seo.google_analytics.order_converter' ] ]

    hgabka_seo.node.listener:
        class: Hgabka\SeoBundle\EventListener\NodeListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: hgabka_node.adaptForm, method: adaptForm }

    hgabka_seo.clone.listener:
        class: Hgabka\SeoBundle\EventListener\CloneListener
        arguments: ['@doctrine.orm.entity_manager', '@hgabka_utils.clone.helper']
        tags:
            - { name: kernel.event_listener, event: hgabka_utils.postDeepCloneAndSave, method: postDeepCloneAndSave }
